--- #YAML:1.0
name:               Data-RuledValidator
version:            0.11
abstract:           data validator with rule
author:
    - Ktat <ktat@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Inspector:     0
    Email::Valid:         0.15
    Email::Valid::Loose:  0.04
    File::Slurp:          0.01
    List::MoreUtils:      0
    Test::Base:           0
    UNIVERSAL::require:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
